language: ruby
rvm: 2.2.2
services: mysql
before_script:
  - mysql -e "SET PASSWORD FOR 'root'@'localhost' = password('root')"
  - mysql -e "CREATE DATABASE flippd"
  - mysql -e "CREATE DATABASE flippd_test"
